"""Model card generator — documents all AI models in the codebase."""

from __future__ import annotations

from datetime import datetime
from typing import Any


# Known model details
MODEL_INFO: dict[str, dict[str, str]] = {
    "gpt-4o": {"provider": "OpenAI", "type": "Chat/Completion", "context": "128K", "training_cutoff": "Oct 2023"},
    "gpt-4o-mini": {"provider": "OpenAI", "type": "Chat/Completion", "context": "128K", "training_cutoff": "Oct 2023"},
    "gpt-4-turbo": {"provider": "OpenAI", "type": "Chat/Completion", "context": "128K", "training_cutoff": "Apr 2023"},
    "gpt-3.5-turbo": {"provider": "OpenAI", "type": "Chat/Completion", "context": "16K", "training_cutoff": "Sep 2021", "status": "DEPRECATED"},
    "o1": {"provider": "OpenAI", "type": "Reasoning", "context": "200K", "training_cutoff": "Oct 2023"},
    "o3": {"provider": "OpenAI", "type": "Reasoning", "context": "200K", "training_cutoff": "Oct 2023"},
    "o3-mini": {"provider": "OpenAI", "type": "Reasoning", "context": "200K", "training_cutoff": "Oct 2023"},
    "o4-mini": {"provider": "OpenAI", "type": "Reasoning", "context": "200K", "training_cutoff": "2024"},
    "claude-opus-4-20250514": {"provider": "Anthropic", "type": "Chat/Completion", "context": "200K", "training_cutoff": "Mar 2025"},
    "claude-sonnet-4-20250514": {"provider": "Anthropic", "type": "Chat/Completion", "context": "200K", "training_cutoff": "Mar 2025"},
    "claude-haiku-4-5-20251001": {"provider": "Anthropic", "type": "Chat/Completion", "context": "200K", "training_cutoff": "Mar 2025"},
    "gemini-2.5-pro": {"provider": "Google", "type": "Chat/Completion", "context": "1M", "training_cutoff": "2024"},
    "gemini-2.5-flash": {"provider": "Google", "type": "Chat/Completion", "context": "1M", "training_cutoff": "2024"},
    "llama-3.1-70b": {"provider": "Meta (self-hosted)", "type": "Chat/Completion", "context": "128K", "training_cutoff": "Dec 2023"},
    "llama-3.1-8b": {"provider": "Meta (self-hosted)", "type": "Chat/Completion", "context": "128K", "training_cutoff": "Dec 2023"},
    "mistral-large": {"provider": "Mistral", "type": "Chat/Completion", "context": "128K", "training_cutoff": "2024"},
}


class ModelCardGenerator:
    """Generate a model card documenting all AI models in the codebase."""

    def generate(self, scan_data: dict[str, Any]) -> str:
        """Generate a markdown model card from scan data."""
        findings = scan_data.get("findings", [])
        risk = scan_data.get("risk", {})

        # Extract unique models
        models: dict[str, dict[str, Any]] = {}
        for f in findings:
            model_name = f.get("model_name", "")
            matched = f.get("matched_value", "") or f.get("matched_text", "")

            # Try to find model name in matched text
            detected_model = model_name
            if not detected_model and matched:
                for known in MODEL_INFO:
                    if known in matched.lower():
                        detected_model = known
                        break

            if not detected_model:
                continue

            if detected_model not in models:
                models[detected_model] = {
                    "provider": f.get("provider", "unknown"),
                    "files": [],
                    "call_count": 0,
                    "has_max_tokens": True,
                }

            file_loc = f"{f.get('file_path', '')}:{f.get('line_number', '')}"
            if file_loc not in models[detected_model]["files"]:
                models[detected_model]["files"].append(file_loc)
            models[detected_model]["call_count"] += 1

            if "max_tokens" in (f.get("pattern_name", "") or "").lower():
                models[detected_model]["has_max_tokens"] = False

        # Generate markdown
        lines = [
            "# AI Model Card",
            "",
            f"*Generated by ScanLLM on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*",
            "",
            "## Overview",
            "",
            f"- **Total AI models detected:** {len(models)}",
            f"- **Risk score:** {risk.get('overall_score', 0)}/100 (Grade {risk.get('grade', '?')})",
            f"- **Total findings:** {len(findings)}",
            "",
        ]

        if not models:
            lines.append("No AI models detected in this codebase.")
            return "\n".join(lines)

        # Provider summary
        providers: dict[str, list[str]] = {}
        for model, info in models.items():
            p = info["provider"]
            if p not in providers:
                providers[p] = []
            providers[p].append(model)

        lines.extend(["## Providers", ""])
        for provider, model_list in sorted(providers.items()):
            lines.append(f"- **{provider}:** {', '.join(model_list)}")
        lines.append("")

        # Individual model cards
        lines.extend(["## Models", ""])
        for model_name, usage_info in sorted(models.items()):
            info = MODEL_INFO.get(model_name, {})
            status = info.get("status", "Active")

            lines.append(f"### {model_name}")
            lines.append("")
            lines.append("| Property | Value |")
            lines.append("|----------|-------|")
            lines.append(f"| Provider | {info.get('provider', usage_info['provider'])} |")
            lines.append(f"| Type | {info.get('type', 'Unknown')} |")
            lines.append(f"| Context Window | {info.get('context', 'Unknown')} |")
            lines.append(f"| Training Cutoff | {info.get('training_cutoff', 'Unknown')} |")
            lines.append(f"| Status | {'**DEPRECATED**' if status == 'DEPRECATED' else status} |")
            lines.append(f"| Usage Count | {usage_info['call_count']} call(s) |")
            lines.append(f"| Has max_tokens | {'Yes' if usage_info['has_max_tokens'] else '**No** (cost risk)'} |")
            lines.append("")

            lines.append("**Used in:**")
            for loc in usage_info["files"][:10]:
                lines.append(f"- `{loc}`")
            if len(usage_info["files"]) > 10:
                lines.append(f"- ... and {len(usage_info['files']) - 10} more")
            lines.append("")

        # Risk assessment
        lines.extend([
            "## Risk Assessment",
            "",
            "| Risk Factor | Status |",
            "|------------|--------|",
        ])

        deprecated = any(MODEL_INFO.get(m, {}).get("status") == "DEPRECATED" for m in models)
        single_provider = len(providers) == 1
        missing_limits = any(not info["has_max_tokens"] for info in models.values())

        lines.append(f"| Deprecated models | {'Yes — upgrade recommended' if deprecated else 'None detected'} |")
        lines.append(f"| Provider concentration | {'Single provider — add fallback' if single_provider else f'{len(providers)} providers'} |")
        lines.append(f"| Unbounded costs | {'Models without max_tokens detected' if missing_limits else 'All calls have limits'} |")
        lines.append("")

        lines.extend(["---", "*Generated by [ScanLLM](https://scanllm.ai)*", ""])
        return "\n".join(lines)
